version: 2
jobs:
  build:
    docker:
      - image: golang:1.12-stretch
    working_directory: /go/src/github.com/lawrencegripper/azbrowse
    steps:
      - checkout 
      - setup_remote_docker: 
         docker_layer_caching: true
      - run: 
          name: Build, Test and *Publish *(only on master in circleci)
          command: make devcontainer-release